### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by boussou** [willfarrell/angular-io-app#2]
Where's the Sql files?
there seems to be differences between this repo & the demo right?

btw, is it an abandonned project?

**Comment by willfarrell** [comment]
Hey, sorry for the super long delay. You have to export it from MySQL Workbench. The project has been put on hold while till after I finish a big client project. I hope to get back to it in a few months.

**Comment by boussou** [comment]
Hi,
either me or you misunderstood: export of what? 
I think my remark was : There is no DB creation files in the repo, so it is pretty useless

Anyway, no problem, thanks for the answer & all the best for your project.
